### ISSUE TITLE
Support Hypertext Application Language (HAL) response

### ISSUE THREAD

**Issue by fabiendupont** [mansam/tackle-hub#2]
The Tackle UI requests `application/hal+json` from the various APIs it talks to. In order to be non disruptive, the Tackle Hub API must also provide HAL+JSON content, instead of or in addition to JSON.

HAL specification by Mike Kelly: https://stateless.group/hal_specification.html
Proposed IETF specification: https://tools.ietf.org/html/draft-kelly-json-hal-08

**Comment by jortel** [comment]
Done.
